weather:
  enable: true
  url: "https://www.mxnzp.com/api/weather/current"
  appId: "xxx"
  appSecret: "xxx"

lottery:
  enable: true
  url: "https://www.mxnzp.com/api/lottery/common/aim_lottery"
  appId: "xxx"
  appSecret: "xxx"

crypto:
  enable: true
  url: "https://api.coingecko.com/api/v3/simple/price"

chat:
  enable: true
  url:"https://api.qingyunke.com/api.php"

weibo:
  enable: true
  url: "https://mrw.so/api.htm"
  key: ""

exchangerate:
  enable: true
  url: "https://www.mxnzp.com/api/exchange_rate/aim"
  appId: ""
  appSecret: ""

football:
enable: true
url: "http://apis.juhe.cn/fapig/football/query"
key: ""

nba:
  enable: true
  url: "http://apis.juhe.cn/fapig/nba/query"
  key: ""

top:
  enable: true
  url: "https://v2.alapi.cn/api/tophub/get"
  key: ""

cook:
  enable: true
  url: "https://way.jd.com/jisuapi/search"
  key: ""

food:
  enable: true
  url1: "https://www.mxnzp.com/api/food_heat/food/search"
  url2: "https://www.mxnzp.com/api/food_heat/food/details"
  appId: ""
  appSecret: ""